# Generated by Django 5.0.3 on 2024-03-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(max_length=255)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_contact_number', models.CharField(max_length=20)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.address')),
            ],
            options={
                'verbose_name_plural': 'suppliers',
            },
        ),
    ]
