# Generated by Django 5.0.3 on 2024-03-29 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("access_type", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("operational_status", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityGateTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_reg", models.CharField(max_length=50)),
                (
                    "trailer_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("purpose", models.TextField()),
                (
                    "security_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gatewarehouse.securitygate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitingBay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "expected_wait_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "security_gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gatewarehouse.securitygate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiting Bay",
                "verbose_name_plural": "Waiting Bays",
            },
        ),
    ]
